# Quick Guide on cleaning a dataset with Pandas 
This script will walk you through some quick steps and guide in clean a raw data you intend to use for analysis or machine learning model building.

## Step 1 : Import the packages needed
The first step will be for you to import the packages needed for the cleaning operation.

In [2]:
import pandas as pd
import pickle as pk

## Step 2 : Read the Raw file into your script
Load all the files you need to clean into you notebook

In [7]:
data  = pd.read_csv("FoodBalanceSheets_E_Africa.csv")

In [9]:
# view imported data
data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2010,Y2010F,Y2011,...,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F,Y2018,Y2018F,Y2019,Y2019F
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,35977.00,*,36661.00,...,39728.00,*,40551.00,*,41389.00,*,42228.00,*,43053.00,*
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,S,0.00,...,0.00,S,0.00,S,0.00,S,0.00,S,0.00,S
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3250.00,Fc,3350.00,...,3417.00,Fc,3443.00,Fc,3383.00,Fc,3382.00,Fc,3493.00,Fc
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,87.27,Fc,88.77,...,91.24,Fc,90.14,Fc,88.64,Fc,90.29,Fc,90.84,Fc
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,84.53,Fc,93.82,...,93.83,Fc,101.03,Fc,97.12,Fc,87.27,Fc,98.14,Fc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91441,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,27.00,Im,27.00,...,29.00,Im,30.00,Im,15.00,Im,16.00,Im,31.00,Im
91442,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,2.11,Fc,2.11,...,2.11,Fc,2.11,Fc,1.02,Fc,1.08,Fc,2.11,Fc
91443,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,2.00,Fc,2.00,...,2.00,Fc,2.00,Fc,1.00,Fc,1.00,Fc,2.00,Fc
91444,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.07,Fc,0.07,...,0.07,Fc,0.07,Fc,0.03,Fc,0.04,Fc,0.07,Fc
91445,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.03,Fc,0.03,...,0.03,Fc,0.03,Fc,0.01,Fc,0.01,Fc,0.03,Fc